import Navbar from '../app/navbar/page.js'; // Correct path to Navbar component
import "./global.css";
import Logo from '../app/Logo/page.js'; // Correct path to Logo component
export const metadata = {
  title: 'Ecommerce Site',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Navbar />
        <Logo/>
        {children}
      </body>
    </html>
  )
}
